version: '3.8'

volumes:
  services_logs:
  
  sqlserver_data:
  


    
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${Sa_Password}
      - MSSQL_PID=Developer
    ports:
      - 1455:1433
    hostname:
        sql-dev
    networks:
      - default
  sqlserver.configurator:
    image: mcr.microsoft.com/mssql/server:2022-latest
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - default
    command: >
      bash -c '
        if [ "$Init" = true ]; then
            sleep 90 &&
      /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P ${Sa_Password:-password123} -d master -i docker-entrypoint-initdb.d/init.sql;
        fi
      touch /config/initialized  # Create a marker file
      echo "Initialization completed" >> /var/log/sqlserver-configurator.log  # Log completion message
        echo "$Init";
        echo "All done!"
        exit 0
        ;'    
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - default
  chrome:
    image: selenium/standalone-chrome:latest
    hostname: chrome
    privileged: true
    shm_size: 2g
    environment:
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=5
    ports:
      - "5900:5900"
      - "4444:4444"
    networks:
      - default
  fetchAnnoucementWorkerService:
    image: fetchannoucementworkerservice
    depends_on:
      rabbitmq:
        condition: service_healthy
      sqlserver.configurator: 
        condition: service_completed_successfully  
    environment:
      - RABBITMQ_HOST=rabbitmq
      - SQLSERVER_HOST=sqlserver
      - SELENIUM_HOST=chrome
    networks:
      - default
    volumes:
      - 'C:\\Logs\\Rental\\Fetch:/app/logs'
  treatAnnoucementWorkerService:
    image: treatannouncementworkerservice
    depends_on:
      rabbitmq:
        condition: service_healthy
      sqlserver.configurator: 
        condition: service_completed_successfully  
    environment:
      - RABBITMQ_HOST=rabbitmq
      - SQLSERVER_HOST=sqlserver
      - SELENIUM_HOST=chrome
    networks:
      - default
    volumes:
      - 'C:\\Logs\Rental\\Treat:/app/logs'
  bankWorkerService:
    image: bankworkerservice
    depends_on:
      sqlserver.configurator: 
        condition: service_completed_successfully  
    environment:
      - SQLSERVER_HOST=sqlserver
      - SELENIUM_HOST=chrome
    networks:
      - default
    volumes:
      - 'C:\\Logs\Rental\\Bank:/app/logs'
  fetchCityWorkerService:
    image: fetchcityworkerservice
    depends_on:
      sqlserver.configurator: 
        condition: service_completed_successfully  
    environment:
      - SQLSERVER_HOST=sqlserver
      - SELENIUM_HOST=chrome
      - RABBITMQ_HOST=rabbitmq
    networks:
      - default
    volumes:
      - 'C:\\Logs\Rental\\City\Fetcher:/app/logs'
  treatCityWorkerService:
    image: treatcityworkerservice
    depends_on:
      sqlserver.configurator: 
        condition: service_completed_successfully  
    environment:
      - SQLSERVER_HOST=sqlserver
      - SELENIUM_HOST=chrome
      - RABBITMQ_HOST=rabbitmq
    networks:
      - default
    volumes:
      - 'C:\\Logs\Rental\\City\Treater:/app/logs'
  rentWorkerService:
    image: rentworkerservice
    depends_on:
      sqlserver.configurator: 
        condition: service_completed_successfully  
    environment:
      - SQLSERVER_HOST=sqlserver
    networks:
      - default
    volumes:
      - 'C:\\Logs\Rental\\Rent:/app/logs'
  rentalWebSite:
    image: rentalinvestmentaidweb
    depends_on:
      sqlserver.configurator: 
        condition: service_completed_successfully  
    environment:
      - SQLSERVER_HOST=sqlserver
      - RABBITMQ_HOST=rabbitmq
    networks:
      - default
    volumes:
      - 'C:\\Logs\Rental\\Rent:/app/logs'
    ports:
      - "8080:8080"

networks:
 default:
  driver: bridge