volumes:
  sqlserver_data:
    
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${Sa_Password}
      - MSSQL_PID=Developer
    ports:
      - 1433:1433
  sqlserver.configurator:
    image: mcr.microsoft.com/mssql/server:2019-latest
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    command: >
      bash -c '
        if [ "$Init" = true ]; then
            sleep 60 &&
      /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P ${Sa_Password:-password123} -d master -i docker-entrypoint-initdb.d/init.sql;
        fi
        echo "$Init";
        echo "All done!";'